version: '2'
services:
  postgres:
    image: dac-postgres
    ports:
     - "5432:5432"
    volumes:
     - postgres-volume-db:/var/lib/postgresql/data/
  web:
    build: .
    image: dac-exemplo-jsf
    ports:
     - "8080:8080"
    links:
     - postgres
volumes:
    postgres-volume-db:
      driver: local
